//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudRoboWpfLoadTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IoTHubConnectionString {
            get {
                return ((string)(this["IoTHubConnectionString"]));
            }
            set {
                this["IoTHubConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dev01,dev02,dev03,dev04")]
        public string DeviceList {
            get {
                return ((string)(this["DeviceList"]));
            }
            set {
                this["DeviceList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public string NumOfLoops {
            get {
                return ((string)(this["NumOfLoops"]));
            }
            set {
                this["NumOfLoops"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""RbHeader"": {
    ""RoutingType"": ""CALL"",
    ""RoutingKeyword"": ""Default"",
    ""AppId"": ""PepperShopApp"",
    ""AppProcessingId"": ""RbSampleApp"",
    ""MessageId"": ""SayHello"",
    ""MessageSeqno"": ""$$Param1$$"",
    ""SendDateTime"": ""$$DateTime$$""
  },
  ""RbBody"": {
    ""visitor"": ""u$$Param2$$""
  }
}")]
        public string TexBoxJson {
            get {
                return ((string)(this["TexBoxJson"]));
            }
            set {
                this["TexBoxJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DateTime.Now")]
        public string TextBoxDateTime {
            get {
                return ((string)(this["TextBoxDateTime"]));
            }
            set {
                this["TextBoxDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Addition")]
        public string ComboBoxP1 {
            get {
                return ((string)(this["ComboBoxP1"]));
            }
            set {
                this["ComboBoxP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Increment:")]
        public string LabelP1 {
            get {
                return ((string)(this["LabelP1"]));
            }
            set {
                this["LabelP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TextBoxIncreP1 {
            get {
                return ((string)(this["TextBoxIncreP1"]));
            }
            set {
                this["TextBoxIncreP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TextBoxStartP1 {
            get {
                return ((string)(this["TextBoxStartP1"]));
            }
            set {
                this["TextBoxStartP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public string TextBoxEndP1 {
            get {
                return ((string)(this["TextBoxEndP1"]));
            }
            set {
                this["TextBoxEndP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Random")]
        public string ComboBoxP2 {
            get {
                return ((string)(this["ComboBoxP2"]));
            }
            set {
                this["ComboBoxP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Value:")]
        public string LabelP2 {
            get {
                return ((string)(this["LabelP2"]));
            }
            set {
                this["LabelP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string TextBoxIncreP2 {
            get {
                return ((string)(this["TextBoxIncreP2"]));
            }
            set {
                this["TextBoxIncreP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TextBoxStartP2 {
            get {
                return ((string)(this["TextBoxStartP2"]));
            }
            set {
                this["TextBoxStartP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public string TextBoxEndP2 {
            get {
                return ((string)(this["TextBoxEndP2"]));
            }
            set {
                this["TextBoxEndP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ComboBoxP3 {
            get {
                return ((string)(this["ComboBoxP3"]));
            }
            set {
                this["ComboBoxP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Increment:")]
        public string LabelP3 {
            get {
                return ((string)(this["LabelP3"]));
            }
            set {
                this["LabelP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TextBoxIncreP3 {
            get {
                return ((string)(this["TextBoxIncreP3"]));
            }
            set {
                this["TextBoxIncreP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TextBoxStartP3 {
            get {
                return ((string)(this["TextBoxStartP3"]));
            }
            set {
                this["TextBoxStartP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public string TextBoxEndP3 {
            get {
                return ((string)(this["TextBoxEndP3"]));
            }
            set {
                this["TextBoxEndP3"] = value;
            }
        }
    }
}
